# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-28 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import tagging.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190226_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=tagging.fields.TagField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='Create_date'),
        ),
    ]
